version: "3.8"
services:
  prefect:
    image: prefecthq/prefect:2.16.4-python3.10
    container_name: prefect
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - ../flows:/app/flows
    working_dir: /app
