# Criando um workflow do GitHub Actions para fazer o deploy de um fluxo do Prefect
# Este arquivo deve ser salvo em .github/workflows/prefect-deploy.yml
# e o repositório deve ser um repositório do GitHub.

name: Deploy Prefect Flow

on: # O deploy será acionado automaticamente quando houver push na branch main
  push:
    branches:
      - main

jobs: # Definindo o job de deploy
  # O job será executado em um ambiente Ubuntu local, daí ainda precisamos das etapas 3 e 4
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências com versões fixas
        run: |
          pip install -U pip
          pip install --no-deps -r requirements.txt
          pip install prefect==2.16.4 griffe==0.35.2

      - name: Verificar conexão com Prefect Cloud
        run: |
          curl -I https://api.prefect.cloud

      - name: Autenticar no Prefect Cloud
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          prefect cloud login --key $PREFECT_API_KEY --workspace uff-eletrica/default

      - name: Deploy do Flow com retry
        run: |
          for i in {1..5}; do
            prefect deploy -n hello-deploy && break || sleep 5
          done

      # - name: Deploy do Flow com Prefect
      #   run: prefect deploy -n hello-deploy
      #   env:
      #     PREFECT_API_URL: http://localhost:4200/api # URL do Prefect Server aqui substituir por http://<SEU_IP_LOCAL>:4200/api
