# Criando um workflow do GitHub Actions para fazer o deploy de um fluxo do Prefect
# Este arquivo deve ser salvo em .github/workflows/prefect-deploy.yml
# e o repositório deve ser um repositório do GitHub.

name: Deploy Prefect Flow

on:   # O deploy será acionado automaticamente quando houver push na branch main
  push:
    branches:
      - main

jobs:  # Definindo o job de deploy
  # O job será executado em um ambiente Ubuntu local, daí ainda precisamos das etapas 3 e 4
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy do Flow com Prefect
        run: prefect deploy -n hello-deploy
        env:
          PREFECT_API_URL: http://localhost:4200/api # URL do Prefect Server aqui substituir por http://<SEU_IP_LOCAL>:4200/api
